# Generated by Django 5.1.4 on 2024-12-21 18:08

import powerpitch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('Student_Id', models.CharField(default=powerpitch.models.Students.generate_student_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Gmail', models.EmailField(max_length=254, unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Branch', models.CharField(max_length=50)),
                ('Roll_No', models.CharField(max_length=10)),
                ('Year', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
