# Generated by Django 5.1.4 on 2024-12-21 18:41

import powerpitch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Student_Id',
            field=models.CharField(default=powerpitch.models.Students.generate_student_id, editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
