# Generated by Django 5.1.4 on 2024-12-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpitch', '0004_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Password',
            field=models.CharField(max_length=128),
        ),
    ]
