# Generated by Django 5.1.4 on 2024-12-22 06:55

import powerpitch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpitch', '0005_alter_students_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('Faculty_Id', models.CharField(default=powerpitch.models.Faculty.generate_faculty_id, editable=False, max_length=11, primary_key=True, serialize=False)),
                ('Library_No', models.CharField(max_length=20)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(choices=[('Asst.Proffesor', 'Asst.Proffesor'), ('Associate ', 'Associate '), ('Professor', 'Professor'), ('programmer', 'programmer')], max_length=50)),
                ('Password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
