# Generated by Django 5.1.4 on 2024-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpitch', '0006_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='Email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
